- name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name AI_ML_Stock_Screener --add-data "models;models" --collect-all xgboost --collect-all scipy --collect-all sklearn dashboard.py
